spring:
    datasource:
        url: jdbc:mysql://localhost:3306/lastpass?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: abc123456
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        # 初始化时建立物理连接连接的个数
        initialSize: 5
        # 最小连接池数量
        minIdle: 5
        # 最大连接池数量
        maxActive: 20
        # 获取连接时最大等待时间(ms)，即60s
        maxWait: 60000
        # 1.Destroy线程会检测连接的间隔时间；2.testWhileIdle的判断依据
        timeBetweenEvictionRunsMillis: 60000
        # 最小生存时间ms
        minEvictableIdleTimeMillis: 300000
        # 用来检测连接是否有效的sql
        validationQuery: SELECT 1 FROM DUAL
        # 申请连接时执行validationQuery检测连接是否有效，启用会降低性能
        testOnBorrow: false
        # 归还连接时执行validationQuery检测连接是否有效，启用会降低性能
        testOnReturn: false
        # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，
        # 执行validationQuery检测连接是否有效，不会降低性能
        testWhileIdle: true
        # 是否缓存preparedStatement，mysql建议关闭
        poolPreparedStatements: false
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,log4j
    freemarker:
        suffix: .html
        charset: utf-8
        # 关闭缓存，模板热部署
        # cache: false
    mvc:
        # 配置静态资源映射路径，/public、/resources路径失效
        static-path-pattern: /static/**
mybatis:
    mapper-locations: classpath:mappers/*.xml
    # 虽然可以配置这项来进行pojo包扫描，但我更倾向于在mapper.xml写全类名
    type-aliases-package: com.rhine.blog.po